#if !canImport(ObjectiveC)
import XCTest

extension JSONIndexTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__JSONIndexTests = [
        ("testIndexDeepIntoAValue", testIndexDeepIntoAValue),
        ("testIndexingIncorrectlyReturnsNil", testIndexingIncorrectlyReturnsNil),
        ("testIndexIntoAnArray", testIndexIntoAnArray),
        ("testIndexIntoAnObject", testIndexIntoAnObject),
        ("testIndexNowhereIntoAValue", testIndexNowhereIntoAValue),
        ("testIndexOnceIntoAValue", testIndexOnceIntoAValue),
    ]
}

extension JSONValueTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__JSONValueTests = [
        ("testArrayRoundTrip", testArrayRoundTrip),
        ("testBoolRoundTrip", testBoolRoundTrip),
        ("testComplexObjectRoundTrip", testComplexObjectRoundTrip),
        ("testDecodeArray", testDecodeArray),
        ("testDecodeBool", testDecodeBool),
        ("testDecodeDouble", testDecodeDouble),
        ("testDecodeNull", testDecodeNull),
        ("testDecodeString", testDecodeString),
        ("testDoubleRoundTrip", testDoubleRoundTrip),
        ("testLetsNestSomeObjectsLikeCrazyRoundTrip", testLetsNestSomeObjectsLikeCrazyRoundTrip),
        ("testNullRoundTrip", testNullRoundTrip),
        ("testStringRoundTrip", testStringRoundTrip),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(JSONIndexTests.__allTests__JSONIndexTests),
        testCase(JSONValueTests.__allTests__JSONValueTests),
    ]
}
#endif
