#if !canImport(ObjectiveC)
import XCTest

extension KombuchaLibTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__KombuchaLibTests = [
        ("testThisIsAPlaceholderTest", testThisIsAPlaceholderTest),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(KombuchaLibTests.__allTests__KombuchaLibTests),
    ]
}
#endif
