#if !canImport(ObjectiveC)
import XCTest

extension KombuchaCLIArgsTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__KombuchaCLIArgsTests = [
        ("testEmptyArgsNoThrows", testEmptyArgsNoThrows),
        ("testParseConfigurationParam", testParseConfigurationParam),
        ("testParseConfigurationParamDefault", testParseConfigurationParamDefault),
        ("testParsePrintErrorsOnlyParamDefault", testParsePrintErrorsOnlyParamDefault),
        ("testParseSnapshotsURLDefaultAlongsideConfig", testParseSnapshotsURLDefaultAlongsideConfig),
        ("testParseWorkURLDefaultAlongsideConfig", testParseWorkURLDefaultAlongsideConfig),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(KombuchaCLIArgsTests.__allTests__KombuchaCLIArgsTests),
    ]
}
#endif
