#if !canImport(ObjectiveC)
import XCTest

extension JUnitTest {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__JUnitTest = [
        ("testCreation", testCreation),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(JUnitTest.__allTests__JUnitTest),
    ]
}
#endif
